version: "3.8"

services:
    # Node.js application
    app:
        container_name: files_manager_node
        image: node:12
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        environment:
            NODE_ENV: development
        command: npm run dev
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            - redis

    # MongoDB
    mongo:
        container_name: files_manager_mongodb
        image: mongo:4.2.8
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db:rw
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    # Redis
    redis:
        container_name: files_manager_redis
        image: redis:6 # Redis version higher version than 5.0.7
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data:rw"

volumes:
    mongo-data:
